(define-library (insider cond-expand)
  (import (insider syntax) (insider error) (insider list)
          (only (insider internal) known-module? features meta))
  (export cond-expand library)
  (include "cond-expand.scm"))
