(library (insider lib-test))
(import
 (insider basic-procedures-test)
 (insider bytevector-test)
 (insider char-test)
 (insider control)
 (insider include-test)
 (insider io-test)
 (insider list-test)
 (insider numeric-test)
 (insider opt-lambda-test)
 (insider string-test)
 (insider syntax)
 (insider syntax-rules-test)
 (insider syntax-test)
 (insider test)
 (insider vector-test))
(export test-lib)

(define (test-lib)
  (test-group "library"
    (test-basic-procedures)
    (test-bytevector)
    (test-char)
    (test-include)
    (test-io)
    (test-list)
    (test-numeric)
    (test-opt-lambda)
    (test-string)
    (test-syntax)
    (test-syntax-transformers)
    (test-vector)))

(when-main-module
 (test-lib))
