(define-library (insider syntax-rules-test)
  (import (insider syntax) (insider basic-procedures) (insider test)
          (insider control) (insider list) (insider numeric) (insider vector))
  (export test-syntax-transformers)
  (include "syntax-rules-test.scm"))
