(define-library (insider syntax-test)
  (import (insider syntax) (insider basic-procedures) (insider numeric)
          (insider list) (insider control) (insider define-values)
          (insider vector) (insider control) (insider test))
  (export test-syntax)
  (include "syntax-test.scm"))
